// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.10 at 07:28:15 PM PET 
//


package com.gpal.DaemonPalomino.models.DB;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlMixed;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import lombok.ToString;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}InvoicedQuantity"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}LineExtensionAmount"/>
 *         &lt;element name="PricingReference">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AlternativeConditionPrice">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PriceAmount"/>
 *                             &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PriceTypeCode"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TaxTotal">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxAmount"/>
 *                   &lt;element name="TaxSubtotal">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxableAmount"/>
 *                             &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxAmount"/>
 *                             &lt;element name="TaxCategory">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Percent"/>
 *                                       &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxExemptionReasonCode"/>
 *                                       &lt;element name="TaxScheme">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
 *                                                 &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Name"/>
 *                                                 &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxTypeCode"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Item">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Description"/>
 *                   &lt;element name="SellersItemIdentification">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Price">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PriceAmount"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "InvoiceLine", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")
@ToString
public class InvoiceLine {

    @XmlElementRefs({
        @XmlElementRef(name = "InvoicedQuantity", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", type = InvoicedQuantity.class),
        @XmlElementRef(name = "Price", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", type = JAXBElement.class),
        @XmlElementRef(name = "PricingReference", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", type = JAXBElement.class),
        @XmlElementRef(name = "ID", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", type = ID.class),
        @XmlElementRef(name = "Item", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", type = JAXBElement.class),
        @XmlElementRef(name = "TaxTotal", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", type = JAXBElement.class),
        @XmlElementRef(name = "LineExtensionAmount", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", type = LineExtensionAmount.class)
    })
    @XmlMixed
    protected List<Object> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InvoicedQuantity }
     * {@link JAXBElement }{@code <}{@link InvoiceLine.Price }{@code >}
     * {@link JAXBElement }{@code <}{@link InvoiceLine.PricingReference }{@code >}
     * {@link ID }
     * {@link String }
     * {@link JAXBElement }{@code <}{@link InvoiceLine.Item }{@code >}
     * {@link JAXBElement }{@code <}{@link InvoiceLine.TaxTotal }{@code >}
     * {@link LineExtensionAmount }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Description"/>
     *         &lt;element name="SellersItemIdentification">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "sellersItemIdentification"
    })
    @XmlRootElement(name = "Item")
    public static class Item {

        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlElement(name = "SellersItemIdentification", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
        protected InvoiceLine.Item.SellersItemIdentification sellersItemIdentification;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the sellersItemIdentification property.
         * 
         * @return
         *     possible object is
         *     {@link InvoiceLine.Item.SellersItemIdentification }
         *     
         */
        public InvoiceLine.Item.SellersItemIdentification getSellersItemIdentification() {
            return sellersItemIdentification;
        }

        /**
         * Sets the value of the sellersItemIdentification property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvoiceLine.Item.SellersItemIdentification }
         *     
         */
        public void setSellersItemIdentification(InvoiceLine.Item.SellersItemIdentification value) {
            this.sellersItemIdentification = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id"
        })
        public static class SellersItemIdentification {

            @XmlElement(name = "ID", required = true)
            protected ID id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link ID }
             *     
             */
            public ID getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link ID }
             *     
             */
            public void setID(ID value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PriceAmount"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "priceAmount"
    })
    @XmlRootElement(name = "Price")
    public static class Price {

        @XmlElement(name = "PriceAmount", required = true)
        protected PriceAmount priceAmount;

        /**
         * Gets the value of the priceAmount property.
         * 
         * @return
         *     possible object is
         *     {@link PriceAmount }
         *     
         */
        public PriceAmount getPriceAmount() {
            return priceAmount;
        }

        /**
         * Sets the value of the priceAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link PriceAmount }
         *     
         */
        public void setPriceAmount(PriceAmount value) {
            this.priceAmount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AlternativeConditionPrice">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PriceAmount"/>
     *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PriceTypeCode"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "alternativeConditionPrice"
    })
    @XmlRootElement(name = "PricingReference")
    public static class PricingReference {

        @XmlElement(name = "AlternativeConditionPrice", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
        protected InvoiceLine.PricingReference.AlternativeConditionPrice alternativeConditionPrice;

        /**
         * Gets the value of the alternativeConditionPrice property.
         * 
         * @return
         *     possible object is
         *     {@link InvoiceLine.PricingReference.AlternativeConditionPrice }
         *     
         */
        public InvoiceLine.PricingReference.AlternativeConditionPrice getAlternativeConditionPrice() {
            return alternativeConditionPrice;
        }

        /**
         * Sets the value of the alternativeConditionPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvoiceLine.PricingReference.AlternativeConditionPrice }
         *     
         */
        public void setAlternativeConditionPrice(InvoiceLine.PricingReference.AlternativeConditionPrice value) {
            this.alternativeConditionPrice = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PriceAmount"/>
         *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}PriceTypeCode"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "priceAmount",
            "priceTypeCode"
        })
        public static class AlternativeConditionPrice {

            @XmlElement(name = "PriceAmount", required = true)
            protected PriceAmount priceAmount;
            @XmlElement(name = "PriceTypeCode")
            @XmlSchemaType(name = "unsignedByte")
            protected String priceTypeCode;

            /**
             * Gets the value of the priceAmount property.
             * 
             * @return
             *     possible object is
             *     {@link PriceAmount }
             *     
             */
            public PriceAmount getPriceAmount() {
                return priceAmount;
            }

            /**
             * Sets the value of the priceAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link PriceAmount }
             *     
             */
            public void setPriceAmount(PriceAmount value) {
                this.priceAmount = value;
            }

            /**
             * Gets the value of the priceTypeCode property.
             * 
             */
            public String getPriceTypeCode() {
                return priceTypeCode;
            }

            /**
             * Sets the value of the priceTypeCode property.
             * 
             */
            public void setPriceTypeCode(String value) {
                this.priceTypeCode = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxAmount"/>
     *         &lt;element name="TaxSubtotal">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxableAmount"/>
     *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxAmount"/>
     *                   &lt;element name="TaxCategory">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Percent"/>
     *                             &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxExemptionReasonCode"/>
     *                             &lt;element name="TaxScheme">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
     *                                       &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Name"/>
     *                                       &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxTypeCode"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taxAmount",
        "taxSubtotal"
    })
    public static class TaxTotal {

        @XmlElement(name = "TaxAmount", required = true)
        protected TaxAmount taxAmount;
        @XmlElement(name = "TaxSubtotal", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
        protected InvoiceLine.TaxTotal.TaxSubtotal taxSubtotal;

        /**
         * Gets the value of the taxAmount property.
         * 
         * @return
         *     possible object is
         *     {@link TaxAmount }
         *     
         */
        public TaxAmount getTaxAmount() {
            return taxAmount;
        }

        /**
         * Sets the value of the taxAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link TaxAmount }
         *     
         */
        public void setTaxAmount(TaxAmount value) {
            this.taxAmount = value;
        }

        /**
         * Gets the value of the taxSubtotal property.
         * 
         * @return
         *     possible object is
         *     {@link InvoiceLine.TaxTotal.TaxSubtotal }
         *     
         */
        public InvoiceLine.TaxTotal.TaxSubtotal getTaxSubtotal() {
            return taxSubtotal;
        }

        /**
         * Sets the value of the taxSubtotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link InvoiceLine.TaxTotal.TaxSubtotal }
         *     
         */
        public void setTaxSubtotal(InvoiceLine.TaxTotal.TaxSubtotal value) {
            this.taxSubtotal = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxableAmount"/>
         *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxAmount"/>
         *         &lt;element name="TaxCategory">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Percent"/>
         *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxExemptionReasonCode"/>
         *                   &lt;element name="TaxScheme">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
         *                             &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Name"/>
         *                             &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxTypeCode"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "taxableAmount",
            "taxAmount",
            "taxCategory"
        })
        public static class TaxSubtotal {

            @XmlElement(name = "TaxableAmount", required = true)
            protected TaxableAmount taxableAmount;
            @XmlElement(name = "TaxAmount", required = true)
            protected TaxAmount taxAmount;
            @XmlElement(name = "TaxCategory", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
            protected InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory taxCategory;

            /**
             * Gets the value of the taxableAmount property.
             * 
             * @return
             *     possible object is
             *     {@link TaxableAmount }
             *     
             */
            public TaxableAmount getTaxableAmount() {
                return taxableAmount;
            }

            /**
             * Sets the value of the taxableAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link TaxableAmount }
             *     
             */
            public void setTaxableAmount(TaxableAmount value) {
                this.taxableAmount = value;
            }

            /**
             * Gets the value of the taxAmount property.
             * 
             * @return
             *     possible object is
             *     {@link TaxAmount }
             *     
             */
            public TaxAmount getTaxAmount() {
                return taxAmount;
            }

            /**
             * Sets the value of the taxAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link TaxAmount }
             *     
             */
            public void setTaxAmount(TaxAmount value) {
                this.taxAmount = value;
            }

            /**
             * Gets the value of the taxCategory property.
             * 
             * @return
             *     possible object is
             *     {@link InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory }
             *     
             */
            public InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory getTaxCategory() {
                return taxCategory;
            }

            /**
             * Sets the value of the taxCategory property.
             * 
             * @param value
             *     allowed object is
             *     {@link InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory }
             *     
             */
            public void setTaxCategory(InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory value) {
                this.taxCategory = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Percent"/>
             *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxExemptionReasonCode"/>
             *         &lt;element name="TaxScheme">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
             *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Name"/>
             *                   &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxTypeCode"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "percent",
                "taxExemptionReasonCode",
                "taxScheme"
            })
            public static class TaxCategory {

                @XmlElement(name = "Percent")
                @XmlSchemaType(name = "unsignedByte")
                protected short percent;
                @XmlElement(name = "TaxExemptionReasonCode")
                @XmlSchemaType(name = "unsignedByte")
                protected short taxExemptionReasonCode;
                @XmlElement(name = "TaxScheme", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
                protected InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme taxScheme;

                /**
                 * Gets the value of the percent property.
                 * 
                 */
                public short getPercent() {
                    return percent;
                }

                /**
                 * Sets the value of the percent property.
                 * 
                 */
                public void setPercent(short value) {
                    this.percent = value;
                }

                /**
                 * Gets the value of the taxExemptionReasonCode property.
                 * 
                 */
                public short getTaxExemptionReasonCode() {
                    return taxExemptionReasonCode;
                }

                /**
                 * Sets the value of the taxExemptionReasonCode property.
                 * 
                 */
                public void setTaxExemptionReasonCode(short value) {
                    this.taxExemptionReasonCode = value;
                }

                /**
                 * Gets the value of the taxScheme property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme }
                 *     
                 */
                public InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme getTaxScheme() {
                    return taxScheme;
                }

                /**
                 * Sets the value of the taxScheme property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme }
                 *     
                 */
                public void setTaxScheme(InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme value) {
                    this.taxScheme = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
                 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Name"/>
                 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}TaxTypeCode"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "id",
                    "name",
                    "taxTypeCode"
                })
                public static class TaxScheme {

                    @XmlElement(name = "ID", required = true)
                    protected ID id;
                    @XmlElement(name = "Name", required = true)
                    protected String name;
                    @XmlElement(name = "TaxTypeCode", required = true)
                    protected String taxTypeCode;

                    /**
                     * Gets the value of the id property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link ID }
                     *     
                     */
                    public ID getID() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link ID }
                     *     
                     */
                    public void setID(ID value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the taxTypeCode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTaxTypeCode() {
                        return taxTypeCode;
                    }

                    /**
                     * Sets the value of the taxTypeCode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTaxTypeCode(String value) {
                        this.taxTypeCode = value;
                    }

                }

            }

        }

    }

}
