//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.10 at 07:28:15 PM PET 
//

package com.gpal.DaemonPalomino.models.DB;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import lombok.ToString;

import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2}UBLExtensions"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}UBLVersionID"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}CustomizationID"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}ID"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}IssueDate"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}IssueTime"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}DueDate"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}InvoiceTypeCode"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}Note"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2}DocumentCurrencyCode"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}Signature"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}AccountingSupplierParty"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}AccountingCustomerParty"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}PaymentTerms"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}TaxTotal"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}LegalMonetaryTotal"/>
 *         &lt;element ref="{urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2}InvoiceLine"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "ublExtensions",
        "ublVersionID",
        "customizationID",
        "id",
        "issueDate",
        "issueTime",
        "dueDate",
        "invoiceTypeCode",
        "note",
        "documentCurrencyCode",
        "signature",
        "accountingSupplierParty",
        "accountingCustomerParty",
        "paymentTerms",
        "taxTotal",
        "legalMonetaryTotal",
        "invoiceLine"
})
@XmlRootElement(name = "Invoice", namespace = "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2")
@ToString
public class Invoice {

    @XmlElement(name = "UBLExtensions", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2", required = true)
    protected UBLExtensions ublExtensions;
    @XmlElement(name = "UBLVersionID", required = true)
    protected BigDecimal ublVersionID;
    @XmlElement(name = "CustomizationID", required = true)
    protected BigDecimal customizationID;
    @XmlElement(name = "ID", required = true)
    protected ID id;
    @XmlElement(name = "IssueDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issueDate;
    @XmlElement(name = "IssueTime", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar issueTime;
    @XmlElement(name = "DueDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDate;
    @XmlElement(name = "InvoiceTypeCode", required = true)
    protected InvoiceTypeCode invoiceTypeCode;
    @XmlElement(name = "Note", required = true)
    protected Note note;
    @XmlElement(name = "DocumentCurrencyCode", required = true)
    protected String documentCurrencyCode;
    @XmlElement(name = "Signature", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
    protected Signature signature;
    @XmlElement(name = "AccountingSupplierParty", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
    protected AccountingSupplierParty accountingSupplierParty;
    @XmlElement(name = "AccountingCustomerParty", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
    protected AccountingCustomerParty accountingCustomerParty;
    @XmlElement(name = "PaymentTerms", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
    protected PaymentTerms paymentTerms;
    @XmlElement(name = "TaxTotal", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
    protected TaxTotal taxTotal;
    @XmlElement(name = "LegalMonetaryTotal", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
    protected LegalMonetaryTotal legalMonetaryTotal;
    @XmlElement(name = "InvoiceLine", namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", required = true)
    protected InvoiceLine invoiceLine;

    /**
     * Gets the value of the ublExtensions property.
     * 
     * @return
     *         possible object is
     *         {@link UBLExtensions }
     * 
     */
    public UBLExtensions getUBLExtensions() {
        return ublExtensions;
    }

    /**
     * Sets the value of the ublExtensions property.
     * 
     * @param value
     *              allowed object is
     *              {@link UBLExtensions }
     * 
     */
    public void setUBLExtensions(UBLExtensions value) {
        this.ublExtensions = value;
    }

    /**
     * Gets the value of the ublVersionID property.
     * 
     * @return
     *         possible object is
     *         {@link BigDecimal }
     * 
     */
    public BigDecimal getUBLVersionID() {
        return ublVersionID;
    }

    /**
     * Sets the value of the ublVersionID property.
     * 
     * @param value
     *              allowed object is
     *              {@link BigDecimal }
     * 
     */
    public void setUBLVersionID(BigDecimal value) {
        this.ublVersionID = value;
    }

    /**
     * Gets the value of the customizationID property.
     * 
     * @return
     *         possible object is
     *         {@link BigDecimal }
     * 
     */
    public BigDecimal getCustomizationID() {
        return customizationID;
    }

    /**
     * Sets the value of the customizationID property.
     * 
     * @param value
     *              allowed object is
     *              {@link BigDecimal }
     * 
     */
    public void setCustomizationID(BigDecimal value) {
        this.customizationID = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *         possible object is
     *         {@link ID }
     * 
     */
    public ID getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *              allowed object is
     *              {@link ID }
     * 
     */
    public void setID(ID value) {
        this.id = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *         possible object is
     *         {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *              allowed object is
     *              {@link XMLGregorianCalendar }
     * 
     */
    public void setIssueDate(XMLGregorianCalendar value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the issueTime property.
     * 
     * @return
     *         possible object is
     *         {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getIssueTime() {
        return issueTime;
    }

    /**
     * Sets the value of the issueTime property.
     * 
     * @param value
     *              allowed object is
     *              {@link XMLGregorianCalendar }
     * 
     */
    public void setIssueTime(XMLGregorianCalendar value) {
        this.issueTime = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *         possible object is
     *         {@link XMLGregorianCalendar }
     * 
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *              allowed object is
     *              {@link XMLGregorianCalendar }
     * 
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the invoiceTypeCode property.
     * 
     * @return
     *         possible object is
     *         {@link InvoiceTypeCode }
     * 
     */
    public InvoiceTypeCode getInvoiceTypeCode() {
        return invoiceTypeCode;
    }

    /**
     * Sets the value of the invoiceTypeCode property.
     * 
     * @param value
     *              allowed object is
     *              {@link InvoiceTypeCode }
     * 
     */
    public void setInvoiceTypeCode(InvoiceTypeCode value) {
        this.invoiceTypeCode = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *         possible object is
     *         {@link Note }
     * 
     */
    public Note getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *              allowed object is
     *              {@link Note }
     * 
     */
    public void setNote(Note value) {
        this.note = value;
    }

    /**
     * Gets the value of the documentCurrencyCode property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getDocumentCurrencyCode() {
        return documentCurrencyCode;
    }

    /**
     * Sets the value of the documentCurrencyCode property.
     * 
     * @param value
     *              allowed object is
     *              {@link String }
     * 
     */
    public void setDocumentCurrencyCode(String value) {
        this.documentCurrencyCode = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *         possible object is
     *         {@link Signature }
     * 
     */
    public Signature getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *              allowed object is
     *              {@link Signature }
     * 
     */
    public void setSignature(Signature value) {
        this.signature = value;
    }

    /**
     * Gets the value of the accountingSupplierParty property.
     * 
     * @return
     *         possible object is
     *         {@link AccountingSupplierParty }
     * 
     */
    public AccountingSupplierParty getAccountingSupplierParty() {
        return accountingSupplierParty;
    }

    /**
     * Sets the value of the accountingSupplierParty property.
     * 
     * @param value
     *              allowed object is
     *              {@link AccountingSupplierParty }
     * 
     */
    public void setAccountingSupplierParty(AccountingSupplierParty value) {
        this.accountingSupplierParty = value;
    }

    /**
     * Gets the value of the accountingCustomerParty property.
     * 
     * @return
     *         possible object is
     *         {@link AccountingCustomerParty }
     * 
     */
    public AccountingCustomerParty getAccountingCustomerParty() {
        return accountingCustomerParty;
    }

    /**
     * Sets the value of the accountingCustomerParty property.
     * 
     * @param value
     *              allowed object is
     *              {@link AccountingCustomerParty }
     * 
     */
    public void setAccountingCustomerParty(AccountingCustomerParty value) {
        this.accountingCustomerParty = value;
    }

    /**
     * Gets the value of the paymentTerms property.
     * 
     * @return
     *         possible object is
     *         {@link PaymentTerms }
     * 
     */
    public PaymentTerms getPaymentTerms() {
        return paymentTerms;
    }

    /**
     * Sets the value of the paymentTerms property.
     * 
     * @param value
     *              allowed object is
     *              {@link PaymentTerms }
     * 
     */
    public void setPaymentTerms(PaymentTerms value) {
        this.paymentTerms = value;
    }

    /**
     * Gets the value of the taxTotal property.
     * 
     * @return
     *         possible object is
     *         {@link TaxTotal }
     * 
     */
    public TaxTotal getTaxTotal() {
        return taxTotal;
    }

    /**
     * Sets the value of the taxTotal property.
     * 
     * @param value
     *              allowed object is
     *              {@link TaxTotal }
     * 
     */
    public void setTaxTotal(TaxTotal value) {
        this.taxTotal = value;
    }

    /**
     * Gets the value of the legalMonetaryTotal property.
     * 
     * @return
     *         possible object is
     *         {@link LegalMonetaryTotal }
     * 
     */
    public LegalMonetaryTotal getLegalMonetaryTotal() {
        return legalMonetaryTotal;
    }

    /**
     * Sets the value of the legalMonetaryTotal property.
     * 
     * @param value
     *              allowed object is
     *              {@link LegalMonetaryTotal }
     * 
     */
    public void setLegalMonetaryTotal(LegalMonetaryTotal value) {
        this.legalMonetaryTotal = value;
    }

    /**
     * Gets the value of the invoiceLine property.
     * 
     * @return
     *         possible object is
     *         {@link InvoiceLine }
     * 
     */
    public InvoiceLine getInvoiceLine() {
        return invoiceLine;
    }

    /**
     * Sets the value of the invoiceLine property.
     * 
     * @param value
     *              allowed object is
     *              {@link InvoiceLine }
     * 
     */
    public void setInvoiceLine(InvoiceLine value) {
        this.invoiceLine = value;
    }

}
