//
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.10 at 07:28:15 PM PET 
//


package com.gpal.DaemonPalomino.models.DB;

import java.math.BigDecimal;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gpal.DaemonPalomino.models.DB package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CityName_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "CityName");
    private final static QName _TaxExemptionReasonCode_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "TaxExemptionReasonCode");
    private final static QName _IssueDate_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "IssueDate");
    private final static QName _DocumentCurrencyCode_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "DocumentCurrencyCode");
    private final static QName _Name_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "Name");
    private final static QName _URI_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "URI");
    private final static QName _RegistrationName_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "RegistrationName");
    private final static QName _CountrySubentity_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "CountrySubentity");
    private final static QName _Description_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "Description");
    private final static QName _UBLVersionID_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "UBLVersionID");
    private final static QName _TaxTypeCode_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "TaxTypeCode");
    private final static QName _AddressTypeCode_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "AddressTypeCode");
    private final static QName _IdentificationCode_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "IdentificationCode");
    private final static QName _Percent_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "Percent");
    private final static QName _Telephone_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "Telephone");
    private final static QName _PaymentMeansID_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "PaymentMeansID");
    private final static QName _ElectronicMail_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "ElectronicMail");
    private final static QName _District_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "District");
    private final static QName _DueDate_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "DueDate");
    private final static QName _IssueTime_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "IssueTime");
    private final static QName _CustomizationID_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "CustomizationID");
    private final static QName _Line_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "Line");
    private final static QName _PriceTypeCode_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", "PriceTypeCode");
    private final static QName _InvoiceLinePrice_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", "Price");
    private final static QName _InvoiceLineTaxTotal_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", "TaxTotal");
    private final static QName _InvoiceLineItem_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", "Item");
    private final static QName _InvoiceLinePricingReference_QNAME = new QName("urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", "PricingReference");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gpal.DaemonPalomino.models.DB
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UBLExtensions }
     * 
     */
    public UBLExtensions createUBLExtensions() {
        return new UBLExtensions();
    }

    /**
     * Create an instance of {@link Signature }
     * 
     */
    public Signature createSignature() {
        return new Signature();
    }

    /**
     * Create an instance of {@link AccountingSupplierParty }
     * 
     */
    public AccountingSupplierParty createAccountingSupplierParty() {
        return new AccountingSupplierParty();
    }

    /**
     * Create an instance of {@link AccountingCustomerParty }
     * 
     */
    public AccountingCustomerParty createAccountingCustomerParty() {
        return new AccountingCustomerParty();
    }

    /**
     * Create an instance of {@link com.gpal.DaemonPalomino.models.DB.TaxTotal }
     * 
     */
    public com.gpal.DaemonPalomino.models.DB.TaxTotal createTaxTotal() {
        return new com.gpal.DaemonPalomino.models.DB.TaxTotal();
    }

    /**
     * Create an instance of {@link InvoiceLine }
     * 
     */
    public InvoiceLine createInvoiceLine() {
        return new InvoiceLine();
    }

    /**
     * Create an instance of {@link InvoiceLine.Item }
     * 
     */
    public InvoiceLine.Item createInvoiceLineItem() {
        return new InvoiceLine.Item();
    }

    /**
     * Create an instance of {@link InvoiceLine.TaxTotal }
     * 
     */
    public InvoiceLine.TaxTotal createInvoiceLineTaxTotal() {
        return new InvoiceLine.TaxTotal();
    }

    /**
     * Create an instance of {@link InvoiceLine.TaxTotal.TaxSubtotal }
     * 
     */
    public InvoiceLine.TaxTotal.TaxSubtotal createInvoiceLineTaxTotalTaxSubtotal() {
        return new InvoiceLine.TaxTotal.TaxSubtotal();
    }

    /**
     * Create an instance of {@link InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory }
     * 
     */
    public InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory createInvoiceLineTaxTotalTaxSubtotalTaxCategory() {
        return new InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory();
    }

    /**
     * Create an instance of {@link InvoiceLine.PricingReference }
     * 
     */
    public InvoiceLine.PricingReference createInvoiceLinePricingReference() {
        return new InvoiceLine.PricingReference();
    }

    /**
     * Create an instance of {@link com.gpal.DaemonPalomino.models.DB.TaxTotal.TaxSubtotal }
     * 
     */
    public com.gpal.DaemonPalomino.models.DB.TaxTotal.TaxSubtotal createTaxTotalTaxSubtotal() {
        return new com.gpal.DaemonPalomino.models.DB.TaxTotal.TaxSubtotal();
    }

    /**
     * Create an instance of {@link com.gpal.DaemonPalomino.models.DB.TaxTotal.TaxSubtotal.TaxCategory }
     * 
     */
    public com.gpal.DaemonPalomino.models.DB.TaxTotal.TaxSubtotal.TaxCategory createTaxTotalTaxSubtotalTaxCategory() {
        return new com.gpal.DaemonPalomino.models.DB.TaxTotal.TaxSubtotal.TaxCategory();
    }

    /**
     * Create an instance of {@link AccountingCustomerParty.Party }
     * 
     */
    public AccountingCustomerParty.Party createAccountingCustomerPartyParty() {
        return new AccountingCustomerParty.Party();
    }

    /**
     * Create an instance of {@link AccountingSupplierParty.Party }
     * 
     */
    public AccountingSupplierParty.Party createAccountingSupplierPartyParty() {
        return new AccountingSupplierParty.Party();
    }

    /**
     * Create an instance of {@link AccountingSupplierParty.Party.PartyLegalEntity }
     * 
     */
    public AccountingSupplierParty.Party.PartyLegalEntity createAccountingSupplierPartyPartyPartyLegalEntity() {
        return new AccountingSupplierParty.Party.PartyLegalEntity();
    }

    /**
     * Create an instance of {@link AccountingSupplierParty.Party.PartyLegalEntity.RegistrationAddress }
     * 
     */
    public AccountingSupplierParty.Party.PartyLegalEntity.RegistrationAddress createAccountingSupplierPartyPartyPartyLegalEntityRegistrationAddress() {
        return new AccountingSupplierParty.Party.PartyLegalEntity.RegistrationAddress();
    }

    /**
     * Create an instance of {@link Signature.DigitalSignatureAttachment }
     * 
     */
    public Signature.DigitalSignatureAttachment createSignatureDigitalSignatureAttachment() {
        return new Signature.DigitalSignatureAttachment();
    }

    /**
     * Create an instance of {@link Signature.SignatoryParty }
     * 
     */
    public Signature.SignatoryParty createSignatureSignatoryParty() {
        return new Signature.SignatoryParty();
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link UBLExtensions.UBLExtension }
     * 
     */
    public UBLExtensions.UBLExtension createUBLExtensionsUBLExtension() {
        return new UBLExtensions.UBLExtension();
    }

    /**
     * Create an instance of {@link ID }
     * 
     */
    public ID createID() {
        return new ID();
    }

    /**
     * Create an instance of {@link InvoiceTypeCode }
     * 
     */
    public InvoiceTypeCode createInvoiceTypeCode() {
        return new InvoiceTypeCode();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link PaymentTerms }
     * 
     */
    public PaymentTerms createPaymentTerms() {
        return new PaymentTerms();
    }

    /**
     * Create an instance of {@link TaxAmount }
     * 
     */
    public TaxAmount createTaxAmount() {
        return new TaxAmount();
    }

    /**
     * Create an instance of {@link LegalMonetaryTotal }
     * 
     */
    public LegalMonetaryTotal createLegalMonetaryTotal() {
        return new LegalMonetaryTotal();
    }

    /**
     * Create an instance of {@link LineExtensionAmount }
     * 
     */
    public LineExtensionAmount createLineExtensionAmount() {
        return new LineExtensionAmount();
    }

    /**
     * Create an instance of {@link TaxInclusiveAmount }
     * 
     */
    public TaxInclusiveAmount createTaxInclusiveAmount() {
        return new TaxInclusiveAmount();
    }

    /**
     * Create an instance of {@link PayableAmount }
     * 
     */
    public PayableAmount createPayableAmount() {
        return new PayableAmount();
    }

    /**
     * Create an instance of {@link InvoicedQuantity }
     * 
     */
    public InvoicedQuantity createInvoicedQuantity() {
        return new InvoicedQuantity();
    }

    /**
     * Create an instance of {@link InvoiceLine.Price }
     * 
     */
    public InvoiceLine.Price createInvoiceLinePrice() {
        return new InvoiceLine.Price();
    }

    /**
     * Create an instance of {@link TaxableAmount }
     * 
     */
    public TaxableAmount createTaxableAmount() {
        return new TaxableAmount();
    }

    /**
     * Create an instance of {@link PriceAmount }
     * 
     */
    public PriceAmount createPriceAmount() {
        return new PriceAmount();
    }

    /**
     * Create an instance of {@link InvoiceLine.Item.SellersItemIdentification }
     * 
     */
    public InvoiceLine.Item.SellersItemIdentification createInvoiceLineItemSellersItemIdentification() {
        return new InvoiceLine.Item.SellersItemIdentification();
    }

    /**
     * Create an instance of {@link InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme }
     * 
     */
    public InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme createInvoiceLineTaxTotalTaxSubtotalTaxCategoryTaxScheme() {
        return new InvoiceLine.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme();
    }

    /**
     * Create an instance of {@link InvoiceLine.PricingReference.AlternativeConditionPrice }
     * 
     */
    public InvoiceLine.PricingReference.AlternativeConditionPrice createInvoiceLinePricingReferenceAlternativeConditionPrice() {
        return new InvoiceLine.PricingReference.AlternativeConditionPrice();
    }

    /**
     * Create an instance of {@link com.gpal.DaemonPalomino.models.DB.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme }
     * 
     */
    public com.gpal.DaemonPalomino.models.DB.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme createTaxTotalTaxSubtotalTaxCategoryTaxScheme() {
        return new com.gpal.DaemonPalomino.models.DB.TaxTotal.TaxSubtotal.TaxCategory.TaxScheme();
    }

    /**
     * Create an instance of {@link AccountingCustomerParty.Party.PartyIdentification }
     * 
     */
    public AccountingCustomerParty.Party.PartyIdentification createAccountingCustomerPartyPartyPartyIdentification() {
        return new AccountingCustomerParty.Party.PartyIdentification();
    }

    /**
     * Create an instance of {@link AccountingCustomerParty.Party.PartyLegalEntity }
     * 
     */
    public AccountingCustomerParty.Party.PartyLegalEntity createAccountingCustomerPartyPartyPartyLegalEntity() {
        return new AccountingCustomerParty.Party.PartyLegalEntity();
    }

    /**
     * Create an instance of {@link AccountingSupplierParty.Party.PartyIdentification }
     * 
     */
    public AccountingSupplierParty.Party.PartyIdentification createAccountingSupplierPartyPartyPartyIdentification() {
        return new AccountingSupplierParty.Party.PartyIdentification();
    }

    /**
     * Create an instance of {@link AccountingSupplierParty.Party.PartyName }
     * 
     */
    public AccountingSupplierParty.Party.PartyName createAccountingSupplierPartyPartyPartyName() {
        return new AccountingSupplierParty.Party.PartyName();
    }

    /**
     * Create an instance of {@link AccountingSupplierParty.Party.Contact }
     * 
     */
    public AccountingSupplierParty.Party.Contact createAccountingSupplierPartyPartyContact() {
        return new AccountingSupplierParty.Party.Contact();
    }

    /**
     * Create an instance of {@link AccountingSupplierParty.Party.PartyLegalEntity.RegistrationAddress.AddressLine }
     * 
     */
    public AccountingSupplierParty.Party.PartyLegalEntity.RegistrationAddress.AddressLine createAccountingSupplierPartyPartyPartyLegalEntityRegistrationAddressAddressLine() {
        return new AccountingSupplierParty.Party.PartyLegalEntity.RegistrationAddress.AddressLine();
    }

    /**
     * Create an instance of {@link AccountingSupplierParty.Party.PartyLegalEntity.RegistrationAddress.Country }
     * 
     */
    public AccountingSupplierParty.Party.PartyLegalEntity.RegistrationAddress.Country createAccountingSupplierPartyPartyPartyLegalEntityRegistrationAddressCountry() {
        return new AccountingSupplierParty.Party.PartyLegalEntity.RegistrationAddress.Country();
    }

    /**
     * Create an instance of {@link Signature.DigitalSignatureAttachment.ExternalReference }
     * 
     */
    public Signature.DigitalSignatureAttachment.ExternalReference createSignatureDigitalSignatureAttachmentExternalReference() {
        return new Signature.DigitalSignatureAttachment.ExternalReference();
    }

    /**
     * Create an instance of {@link Signature.SignatoryParty.PartyIdentification }
     * 
     */
    public Signature.SignatoryParty.PartyIdentification createSignatureSignatoryPartyPartyIdentification() {
        return new Signature.SignatoryParty.PartyIdentification();
    }

    /**
     * Create an instance of {@link Signature.SignatoryParty.PartyName }
     * 
     */
    public Signature.SignatoryParty.PartyName createSignatureSignatoryPartyPartyName() {
        return new Signature.SignatoryParty.PartyName();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "CityName")
    public JAXBElement<String> createCityName(String value) {
        return new JAXBElement<String>(_CityName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "TaxExemptionReasonCode")
    public JAXBElement<Short> createTaxExemptionReasonCode(Short value) {
        return new JAXBElement<Short>(_TaxExemptionReasonCode_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "IssueDate")
    public JAXBElement<XMLGregorianCalendar> createIssueDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IssueDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "DocumentCurrencyCode")
    public JAXBElement<String> createDocumentCurrencyCode(String value) {
        return new JAXBElement<String>(_DocumentCurrencyCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "URI")
    public JAXBElement<String> createURI(String value) {
        return new JAXBElement<String>(_URI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "RegistrationName")
    public JAXBElement<String> createRegistrationName(String value) {
        return new JAXBElement<String>(_RegistrationName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "CountrySubentity")
    public JAXBElement<String> createCountrySubentity(String value) {
        return new JAXBElement<String>(_CountrySubentity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "UBLVersionID")
    public JAXBElement<BigDecimal> createUBLVersionID(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_UBLVersionID_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "TaxTypeCode")
    public JAXBElement<String> createTaxTypeCode(String value) {
        return new JAXBElement<String>(_TaxTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "AddressTypeCode")
    public JAXBElement<Short> createAddressTypeCode(Short value) {
        return new JAXBElement<Short>(_AddressTypeCode_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "IdentificationCode")
    public JAXBElement<String> createIdentificationCode(String value) {
        return new JAXBElement<String>(_IdentificationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "Percent")
    public JAXBElement<Short> createPercent(Short value) {
        return new JAXBElement<Short>(_Percent_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "Telephone")
    public JAXBElement<String> createTelephone(String value) {
        return new JAXBElement<String>(_Telephone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "PaymentMeansID")
    public JAXBElement<String> createPaymentMeansID(String value) {
        return new JAXBElement<String>(_PaymentMeansID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "ElectronicMail")
    public JAXBElement<String> createElectronicMail(String value) {
        return new JAXBElement<String>(_ElectronicMail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "District")
    public JAXBElement<String> createDistrict(String value) {
        return new JAXBElement<String>(_District_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "DueDate")
    public JAXBElement<XMLGregorianCalendar> createDueDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DueDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "IssueTime")
    public JAXBElement<XMLGregorianCalendar> createIssueTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IssueTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "CustomizationID")
    public JAXBElement<BigDecimal> createCustomizationID(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CustomizationID_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "Line")
    public JAXBElement<String> createLine(String value) {
        return new JAXBElement<String>(_Line_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2", name = "PriceTypeCode")
    public JAXBElement<Short> createPriceTypeCode(Short value) {
        return new JAXBElement<Short>(_PriceTypeCode_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceLine.Price }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", name = "Price", scope = InvoiceLine.class)
    public JAXBElement<InvoiceLine.Price> createInvoiceLinePrice(InvoiceLine.Price value) {
        return new JAXBElement<InvoiceLine.Price>(_InvoiceLinePrice_QNAME, InvoiceLine.Price.class, InvoiceLine.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceLine.TaxTotal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", name = "TaxTotal", scope = InvoiceLine.class)
    public JAXBElement<InvoiceLine.TaxTotal> createInvoiceLineTaxTotal(InvoiceLine.TaxTotal value) {
        return new JAXBElement<InvoiceLine.TaxTotal>(_InvoiceLineTaxTotal_QNAME, InvoiceLine.TaxTotal.class, InvoiceLine.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceLine.Item }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", name = "Item", scope = InvoiceLine.class)
    public JAXBElement<InvoiceLine.Item> createInvoiceLineItem(InvoiceLine.Item value) {
        return new JAXBElement<InvoiceLine.Item>(_InvoiceLineItem_QNAME, InvoiceLine.Item.class, InvoiceLine.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceLine.PricingReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", name = "PricingReference", scope = InvoiceLine.class)
    public JAXBElement<InvoiceLine.PricingReference> createInvoiceLinePricingReference(InvoiceLine.PricingReference value) {
        return new JAXBElement<InvoiceLine.PricingReference>(_InvoiceLinePricingReference_QNAME, InvoiceLine.PricingReference.class, InvoiceLine.class, value);
    }

}
